version: '3.9'

services:
  database:
    image: postgis/postgis:14-3.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin_user
      - POSTGRES_DB=mesh-network-db
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data