spring:
  application:
    name: mesh-network-app
  # Database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mesh-network-db
    username: admin_user
    password: admin_password
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
logging:
  level:
    org.hibernate.type.descriptor.sql: trace